package code_test

import (
	"context"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCliCommands(t *testing.T) {
	mainPath := "./../cmd/hexlet-path-size/main.go"
	tempDir := t.TempDir()
	compiledPath := filepath.Join(tempDir, "hexlet-path-size")

	ctx := context.Background()

	//nolint:gosec // G204: paths are hardcoded and controlled by the test, no risk of command injection
	cmd := exec.CommandContext(ctx, "go", "build", "-o", compiledPath, mainPath)
	err := cmd.Run()
	require.NoError(t, err, "failed to compile binary")

	testCases := []struct {
		name         string
		args         []string
		expectError  bool
		outputSubset string
	}{
		// --- Group 1: System / Help ---
		{
			name:         "help flag long",
			args:         []string{"--help"},
			expectError:  false,
			outputSubset: "USAGE:",
		},
		{
			name:         "help flag short",
			args:         []string{"-h"},
			expectError:  false,
			outputSubset: "GLOBAL OPTIONS:",
		},

		// --- Group 2: User Validation Errors (Should fail cleanly) ---
		{
			name:        "missing path argument",
			args:        []string{},
			expectError: true,
		},
		{
			name:        "too many arguments",
			args:        []string{"./../testdata/file1.txt", "./../testdata/in"},
			expectError: true,
		},
		{
			name:        "unknown global flag",
			args:        []string{"--invalid-flag-xyz", "./../testdata/file1.txt"},
			expectError: true,
		},
		{
			name:        "non-existent target path",
			args:        []string{"./../testdata/does-not-exist-at-all"},
			expectError: true,
		},

		// --- Group 3: Happy Path / Execution ---
		{
			name:         "valid file raw bytes",
			args:         []string{"./../testdata/file1.txt"},
			expectError:  false,
			outputSubset: "2906B",
		},
		{
			name:         "valid directory human readable",
			args:         []string{"-H", "./../testdata/in"},
			expectError:  false,
			outputSubset: "2.4KB",
		},
		{
			name:         "valid directory recursive and hidden",
			args:         []string{"-r", "-a", "./../testdata"},
			expectError:  false,
			outputSubset: "5418B",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			//nolint:gosec // G204: binary path is generated by t.TempDir(), arguments are controlled inside the table
			runCmd := exec.CommandContext(ctx, compiledPath, tc.args...)

			output, runErr := runCmd.CombinedOutput()

			if tc.expectError {
				require.Error(t, runErr, "expected command to fail with exit code 1")
			} else {
				require.NoError(t, runErr, "expected command to succeed with exit code 0")
			}

			if tc.outputSubset != "" {
				require.Contains(t, string(output), tc.outputSubset)
			}
		})
	}
}
