package main_test

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCliCommands(t *testing.T) {
	tempDir := t.TempDir()
	compiledPath := filepath.Join(tempDir, "hexlet-path-size")
	sampleFile := filepath.Join(tempDir, "sample.txt")
	require.NoError(t, os.WriteFile(sampleFile, []byte("hello"), 0o600))

	ctx := context.Background()

	//nolint:gosec // G204: paths are controlled by the test, no risk of command injection
	buildCmd := exec.CommandContext(ctx, "go", "build", "-o", compiledPath, ".")
	buildCmd.Dir = filepath.Join("..", "..", "cmd", "hexlet-path-size")

	err := buildCmd.Run()
	require.NoError(t, err, "failed to compile binary")

	testCases := []struct {
		name            string
		args            []string
		expectError     bool
		stdoutSubstring string
		stderrSubstring string
	}{
		{
			name:            "non-existent target path",
			args:            []string{filepath.Join(tempDir, "does-not-exist-at-all")},
			expectError:     true,
			stderrSubstring: "path does not exist: " + filepath.Join(tempDir, "does-not-exist-at-all"),
		},
		{
			name:            "prints size and path separated by tab",
			args:            []string{sampleFile},
			stdoutSubstring: "5B\t" + sampleFile,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			//nolint:gosec // G204: binary path is generated by t.TempDir(), arguments are controlled inside the table
			runCmd := exec.CommandContext(ctx, compiledPath, tc.args...)

			var stdout, stderr bytes.Buffer
			runCmd.Stdout = &stdout
			runCmd.Stderr = &stderr

			runErr := runCmd.Run()

			if tc.expectError {
				require.Error(t, runErr, "expected command to fail with exit code 1")
			} else {
				require.NoError(t, runErr, "expected command to succeed with exit code 0")
			}

			if tc.stdoutSubstring != "" {
				assert.Equal(t, tc.stdoutSubstring, strings.TrimSpace(stdout.String()))
				assert.Empty(t, stderr.String())
			}

			if tc.stderrSubstring != "" {
				assert.Equal(t, tc.stderrSubstring, strings.TrimSpace(stderr.String()))
				assert.Empty(t, stdout.String())
			}
		})
	}
}
