package main_test

import (
	"bytes"
	"context"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCliCommands(t *testing.T) {
	tempDir := t.TempDir()
	compiledPath := filepath.Join(tempDir, "hexlet-path-size")
	testdata := "testdata"

	ctx := context.Background()

	//nolint:gosec // G204: paths are controlled by the test, no risk of command injection
	buildCmd := exec.CommandContext(ctx, "go", "build", "-o", compiledPath, ".")
	buildCmd.Dir = filepath.Join("..", "..", "cmd", "hexlet-path-size")

	err := buildCmd.Run()
	require.NoError(t, err, "failed to compile binary")

	testCases := []struct {
		name            string
		args            []string
		expectError     bool
		stdoutSubstring string
		stderrSubstring string
	}{
		{
			name:            "help flag long",
			args:            []string{"--help"},
			stdoutSubstring: "USAGE:",
		},
		{
			name:            "help flag short",
			args:            []string{"-h"},
			stdoutSubstring: "GLOBAL OPTIONS:",
		},
		{
			name:            "missing path argument",
			args:            []string{},
			expectError:     true,
			stderrSubstring: "incorrect usage",
		},
		{
			name:            "too many arguments",
			args:            []string{filepath.Join(testdata, "file1.txt"), filepath.Join(testdata, "in")},
			expectError:     true,
			stderrSubstring: "incorrect usage",
		},
		{
			name:            "unknown global flag",
			args:            []string{"--invalid-flag-xyz", filepath.Join(testdata, "file1.txt")},
			expectError:     true,
			stderrSubstring: "Incorrect Usage",
		},
		{
			name:            "non-existent target path",
			args:            []string{filepath.Join(testdata, "does-not-exist-at-all")},
			expectError:     true,
			stderrSubstring: "path not exists",
		},
		{
			name:            "direct hidden file ignored without all",
			args:            []string{filepath.Join(testdata, "in", ".file3.txt")},
			stdoutSubstring: "0B\t" + filepath.Join(testdata, "in", ".file3.txt"),
		},
		{
			name:            "valid file raw bytes",
			args:            []string{filepath.Join(testdata, "file1.txt")},
			stdoutSubstring: "2906B\t" + filepath.Join(testdata, "file1.txt"),
		},
		{
			name:            "valid directory human readable",
			args:            []string{"-H", filepath.Join(testdata, "in")},
			stdoutSubstring: "2.4KB\t" + filepath.Join(testdata, "in"),
		},
		{
			name:            "valid directory recursive and hidden",
			args:            []string{"-r", "-a", testdata},
			stdoutSubstring: "5421B\t" + testdata,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			//nolint:gosec // G204: binary path is generated by t.TempDir(), arguments are controlled inside the table
			runCmd := exec.CommandContext(ctx, compiledPath, tc.args...)

			var stdout, stderr bytes.Buffer
			runCmd.Stdout = &stdout
			runCmd.Stderr = &stderr

			runErr := runCmd.Run()

			if tc.expectError {
				require.Error(t, runErr, "expected command to fail with exit code 1")
			} else {
				require.NoError(t, runErr, "expected command to succeed with exit code 0")
			}

			if tc.stdoutSubstring != "" {
				require.Contains(t, stdout.String(), tc.stdoutSubstring)
			}

			if tc.stderrSubstring != "" {
				require.Contains(t, stderr.String(), tc.stderrSubstring)
			}
		})
	}
}
